# Generated by Django 4.1.2 on 2022-10-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_user_alter_job_industry_candidatesapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesapplied',
            name='resume',
            field=models.CharField(max_length=200),
        ),
    ]
