# Generated by Django 4.1.2 on 2022-10-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_candidatesapplied_job_alter_job_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jobtype',
            new_name='jobType',
        ),
    ]
